import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'



import "./globals.css";
import { ConvexClientProvider } from "@/ConvexClientProvider";
import { cn } from "@/lib/utils";
import NavBar from "@/components/home/NavBar";
import { Footer } from "@/components/home/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignOutUrl={'/home'}
    >
      <ConvexClientProvider>
        <html lang="en">
          <body
            className={cn("bg-[url('/assets/images/background.jpg')]  bg-cover bg-center min-h-screen ",  `${geistSans.variable} ${geistMono.variable} antialiased`)}>
            <NavBar />
            {children}
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
